name: Code Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest pytest-asyncio
          pip install black

      - name: Analysing the code with Pylint
        run: |
          pylint --errors-only --clear-cache-post-run y app/

      - name: Testing with Pytest
        run: |
          pytest app --cov=app --disable-warnings --asyncio-mode auto
      
      - name: Format check with Black
        run: |
          black --check .
