name: Build and Deploy Docker Image

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["Code Quality Checks"]
    types: [completed]

jobs:
  build-and-push:
    if: ${{ github.event_name == 'push' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          files: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/private-repo-test:latest
