name: Build and Deploy Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch Current Version from MongoDB
        run: |
          response=$(curl --location --request POST '${{ env.MONGODB_DATA_API_ENDPOINT }}/findOne' --header 'Content-Type: application/json' --header 'Access-Control-Request-Headers: *' --header 'api-key: ${{ secrets.MONGO_DATA_API_TOKEN }}' --data-raw '{
            "collection":"${{ secrets.MONGODB_COLLECTION }}",
            "database":"${{ secrets.MONGODB_DATABASE }}",
            "dataSource":"${{ secrets.MONGODB_DATA_SOURCE }}",
            "filter": {
                "project": "universe"
            }
          }')
          version=$(echo $response | jq -r '.document | "\(.x).\(.y).\(.z)"')
          echo "version=$version" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          files: ${{ env.DOCKER_FILEPATH || './Dockerfile' }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.version }}

      - name: Update Current Version in MongoDB
        run: |
          response=$(curl --location --request POST '${{ env.MONGODB_DATA_API_ENDPOINT }}/updateOne' --header 'Content-Type: application/json' --header 'Access-Control-Request-Headers: *' --header 'api-key: ${{ secrets.MONGO_DATA_API_TOKEN }}' --data-raw '{
            "collection":"${{ secrets.MONGODB_COLLECTION }}",
            "database":"${{ secrets.MONGODB_DATABASE }}",
            "dataSource":"${{ secrets.MONGODB_DATA_SOURCE }}",
            "filter": {
              "project": "universe"
            },
            "update": {
              "$inc": {
                "z": 1
              }
            }
          }')
          echo "Update Response: $response"
          if [[ "$response" != '{"matchedCount":1,"modifiedCount":1}' ]]; then
            echo "Update to New Version failed"
            exit 1
          fi
